[package]
name = "cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cpu_1"
path = "src/cpu_1.rs"

[[bin]]
name = "cpu_2"
path = "src/cpu_2.rs"

[[bin]]
name = "cpu_3"
path = "src/cpu_3.rs"
