---
- hosts: localhost
  gather_facts: false

  vars:
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      replicas: 4

  tasks:
      - name: déploiement de docker-go (k8s_scale).
        k8s_scale:
            api_version: v1
            kind: Deployment
            name: docker-go
            namespace: default
            replicas: "{{ replicas }}"
            wait: false
