---
- hosts: localhost
  gather_facts: false

  vars:
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      replicas: 4

  tasks:
      - name: Déploiement de docker-go (strategic-merge).
        k8s:
            state: present
            merge_type: strategic-merge
            definition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                    name: docker-go
                    namespace: default
                spec:
                    replicas: "{{ replicas }}"
