[package]
name = "ch05-structs"
version = "0.1.0"
authors = ["PhiSyX <738010+PhiSyX@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
